
export const theme = {
    colors: {
        bg: '#FFFFFF',
        bgAlt: '#F7FAFC',
        bgheader: '#FFFFFF',
        bgdev: '#FFFFFF',
        surface: '#FFFFFF',
        surfaceTint: '#EAF6FD',
        surfaceHover: '#EAF6FD',
        border: '#E2E8F0',
        brand1: '#1BA3E8',
        brand2: '#5CCBF5',
        accentHover: '#0B84C4',
        accentDeep: '#085C87',
        navy: '#0B1220',
        navySoft: '#0D1729',
        text: '#0F172A',
        textMuted: '#64748B',
        white: '#FFFFFF',
    },
    radius: {
        sm: '6px',
        md: '10px',
        pill: '999px',
        circle: '50%',
    },
    typography: {
        fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
        fontFamilyMono: "'JetBrains Mono', ui-monospace, monospace",

        // Escala modular (base 16px, razão 1.25 - "terça maior")
        fontSize: {
            'bg-text-u': '117px',
            h1: '64px',
            h2: '32px',
            button: '20px',
            article: '16px',
            paragraph: '16px',
            labelMedium: '14px',
            labelLight: '14px',
            xs: '13px',
            sm: '16px',
            md: '20px',
            lg: '25px',
            xl: '31px',
            xxl: '39px',
            xxxl: '49px',
            display: '61px',
        },

        fontWeight: {
            regular: '400',
            light: '300',
            medium: '500',
            bold: '700',
        },

        lineHeight: {
            'bg-text-u': '134px',
            h1: '72px',
            h2: '36px',
            button: '24px',
            article: '32px',
            paragraph: '18px',
            labelMedium: '16px',
            labelLight: '16px',
        },
    },
};
